version: "3"

services:
  database:
    build: ./postgres
    container_name: pg_container
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  app:
    build: ./node
    container_name: node_container
    links:
      - database
    depends_on: 
      database:
        condition: service_healthy
    environment:
      - CONVICTIONAL_SERVER_PORT=3000
      - CONVICTIONAL_PG_USER=convictional
      - CONVICTIONAL_PG_HOST=database
      - CONVICTIONAL_PG_PORT=5432
      - CONVICTIONAL_PG_PASSWORD=convictional
      - CONVICTIONAL_PG_DATABASE=convictional
    ports:
      - "3000:3000"
    depends_on:
      - database
